const actions = {
  GAME_PUSH_MESSAGE: 'GAME_PUSH_MESSAGE',
  GAME_SUBMIT_COMMAND: 'GAME_SUBMIT_COMMAND',
  SCENE_UPDATE: 'SCENE_UPDATE',
  USER_ADD_ITEM: 'USER_ADD_ITEM',
  USER_MOVE: 'USER_MOVE',
  USER_REMOVE_ITEM: 'USER_REMOVE_ITEM',
};

export default actions;
