const actions = {
  GAME_PUSH_MESSAGE: 'GAME_PUSH_MESSAGE',
  GAME_SUBMIT_COMMAND: 'GAME_SUBMIT_COMMAND',
  SCENE_SET_FLAG: 'SCENE_SET_FLAG',
  USER_GIVE_ITEM: 'USER_GIVE_ITEM',
  USER_MOVE: 'USER_MOVE',
  USER_TAKE_ITEM: 'USER_TAKE_ITEM',
};

export default actions;
